# Generated by Django 5.2 on 2025-05-05 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("specialties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("surname", models.CharField(max_length=150)),
                ("patronymic", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="specialties.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "master",
                "verbose_name_plural": "masters",
                "db_table": "masters",
            },
        ),
    ]
