# Generated by Django 5.2 on 2025-05-06 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specialties.specialty'),
        ),
    ]
