# Generated by Django 5.2 on 2025-06-10 11:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterField(
            model_name="client",
            name="number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="RU", unique=True, verbose_name="Телефон"
            ),
        ),
    ]
