# Generated by Django 5.2 on 2025-05-10 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_alter_client_number"),
        ("masters", "0002_alter_master_specialty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата приема")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Доступен для записи"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="masters.master",
                        verbose_name="Мастер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на прием",
                "verbose_name_plural": "Записи на прием",
                "ordering": ["date", "start_time"],
                "unique_together": {("master", "date", "start_time")},
            },
        ),
    ]
