# Generated by Django 5.2 on 2025-06-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0002_alter_master_specialty"),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyschedule",
            name="break_end",
            field=models.TimeField(
                blank=True, default="13:00", null=True, verbose_name="Конец перерыва"
            ),
        ),
        migrations.AlterField(
            model_name="dailyschedule",
            name="break_start",
            field=models.TimeField(
                blank=True, default="12:00", null=True, verbose_name="Начало перерыва"
            ),
        ),
        migrations.AlterField(
            model_name="weeklyschedule",
            name="master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="masters.master"
            ),
        ),
        migrations.AlterField(
            model_name="weeklyschedule",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
