# Generated by Django 5.2 on 2025-06-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_alter_dailyschedule_break_end_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="dailyschedule",
            table="dailySchedules",
        ),
        migrations.AlterModelTable(
            name="weeklyschedule",
            table="weeklySchedule",
        ),
    ]
